version: '3.8'

services:
  dti-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: dti-calculator
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80